CREATE TABLE IF NOT EXISTS users (
    user_id      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_name    VARCHAR(50)  NOT NULL UNIQUE,
    user_pwd     VARCHAR(255) NOT NULL,
    email        VARCHAR(100) NOT NULL UNIQUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
